apiVersion: v1
kind: Secret
metadata:
  name: {{ include "authcore.name" . }}-secret
  labels:
    app.kubernetes.io/name: {{ include "authcore.name" . }}-secret
    helm.sh/chart: {{ include "authcore.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  authcore-password: {{ include "authcore.setup.adminPassword" . }}
  secret.yaml: |-
{{- /* 62^43 > 2^256 */}}
    secret_key_base: {{ randAlphaNum 43 | sha256sum | quote }}
{{- /* P256 ECDSA KEY */}}
    access_token_private_key: |-
      {{ genPrivateKey "ecdsa" | indent 6 | trim }}
{{- if .Values.secret }}
{{ toYaml .Values.secret | indent 4 }}
{{- end }}