apiVersion: v1
kind: Service
metadata:
  name: {{ include "authcore.fullname" . }}-apiserver
  labels:
    app.kubernetes.io/name: {{ include "authcore.name" . }}-apiserver
    helm.sh/chart: {{ include "authcore.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.api.type }}
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.grpc.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app.kubernetes.io/name: {{ include "authcore.name" . }}-apiserver
    app.kubernetes.io/instance: {{ .Release.Name }}

